window.esdocSearchIndex = [
  [
    "aureooms-js-array/src/reduce/all.js~all",
    "function/index.html#static-function-all",
    "<span>all</span> <span class=\"search-result-import-path\">aureooms-js-array/src/reduce/all.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/alloc.js~alloc",
    "function/index.html#static-function-alloc",
    "<span>alloc</span> <span class=\"search-result-import-path\">aureooms-js-array/src/alloc.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/reduce/any.js~any",
    "function/index.html#static-function-any",
    "<span>any</span> <span class=\"search-result-import-path\">aureooms-js-array/src/reduce/any.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/argmax.js~argmax",
    "function/index.html#static-function-argmax",
    "<span>argmax</span> <span class=\"search-result-import-path\">aureooms-js-array/src/argmax.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/argmin.js~argmin",
    "function/index.html#static-function-argmin",
    "<span>argmin</span> <span class=\"search-result-import-path\">aureooms-js-array/src/argmin.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/chain.js~chain",
    "function/index.html#static-function-chain",
    "<span>chain</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/chain.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/combinations.js~combinations",
    "function/index.html#static-function-combinations",
    "<span>combinations</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/combinations.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/combinationswithrepetition.js~combinationswithrepetition",
    "function/index.html#static-function-combinationswithrepetition",
    "<span>combinationswithrepetition</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/combinationswithrepetition.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/compress.js~compress",
    "function/index.html#static-function-compress",
    "<span>compress</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/compress.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/copy.js~copy",
    "function/index.html#static-function-copy",
    "<span>copy</span> <span class=\"search-result-import-path\">aureooms-js-array/src/copy.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/dropwhile.js~dropwhile",
    "function/index.html#static-function-dropwhile",
    "<span>dropwhile</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/dropwhile.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/each.js~each",
    "function/index.html#static-function-each",
    "<span>each</span> <span class=\"search-result-import-path\">aureooms-js-array/src/each.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/enumerate.js~enumerate",
    "function/index.html#static-function-enumerate",
    "<span>enumerate</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/enumerate.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/fill.js~fill",
    "function/index.html#static-function-fill",
    "<span>fill</span> <span class=\"search-result-import-path\">aureooms-js-array/src/fill.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/fillfn.js~fillfn",
    "function/index.html#static-function-fillfn",
    "<span>fillfn</span> <span class=\"search-result-import-path\">aureooms-js-array/src/fillfn.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/filter.js~filter",
    "function/index.html#static-function-filter",
    "<span>filter</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/filter.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/filterfalse.js~filterfalse",
    "function/index.html#static-function-filterfalse",
    "<span>filterfalse</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/filterfalse.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/get.js~get",
    "function/index.html#static-function-get",
    "<span>get</span> <span class=\"search-result-import-path\">aureooms-js-array/src/get.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/group.js~group",
    "function/index.html#static-function-group",
    "<span>group</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/group.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/iota.js~iota",
    "function/index.html#static-function-iota",
    "<span>iota</span> <span class=\"search-result-import-path\">aureooms-js-array/src/iota.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/islice.js~islice",
    "function/index.html#static-function-islice",
    "<span>islice</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/islice.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/map.js~map",
    "function/index.html#static-function-map",
    "<span>map</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/map.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/max.js~max",
    "function/index.html#static-function-max",
    "<span>max</span> <span class=\"search-result-import-path\">aureooms-js-array/src/max.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/min.js~min",
    "function/index.html#static-function-min",
    "<span>min</span> <span class=\"search-result-import-path\">aureooms-js-array/src/min.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/permutations.js~permutations",
    "function/index.html#static-function-permutations",
    "<span>permutations</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/permutations.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/utils/pick.js~pick",
    "function/index.html#static-function-pick",
    "<span>pick</span> <span class=\"search-result-import-path\">aureooms-js-array/src/utils/pick.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/product.js~product",
    "function/index.html#static-function-product",
    "<span>product</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/product.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/utils/range.js~range",
    "function/index.html#static-function-range",
    "<span>range</span> <span class=\"search-result-import-path\">aureooms-js-array/src/utils/range.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/realloc.js~realloc",
    "function/index.html#static-function-realloc",
    "<span>realloc</span> <span class=\"search-result-import-path\">aureooms-js-array/src/realloc.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/reduce/reduce.js~reduce",
    "function/index.html#static-function-reduce",
    "<span>reduce</span> <span class=\"search-result-import-path\">aureooms-js-array/src/reduce/reduce.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/repeat.js~repeat",
    "function/index.html#static-function-repeat",
    "<span>repeat</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/repeat.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/repr.js~repr",
    "function/index.html#static-function-repr",
    "<span>repr</span> <span class=\"search-result-import-path\">aureooms-js-array/src/repr.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/reverse.js~reverse",
    "function/index.html#static-function-reverse",
    "<span>reverse</span> <span class=\"search-result-import-path\">aureooms-js-array/src/reverse.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/reversed.js~reversed",
    "function/index.html#static-function-reversed",
    "<span>reversed</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/reversed.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/rotate.js~rotate",
    "function/index.html#static-function-rotate",
    "<span>rotate</span> <span class=\"search-result-import-path\">aureooms-js-array/src/rotate.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/set.js~set",
    "function/index.html#static-function-set",
    "<span>set</span> <span class=\"search-result-import-path\">aureooms-js-array/src/set.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/slice.js~slice",
    "function/index.html#static-function-slice",
    "<span>slice</span> <span class=\"search-result-import-path\">aureooms-js-array/src/slice.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/sort.js~sort",
    "function/index.html#static-function-sort",
    "<span>sort</span> <span class=\"search-result-import-path\">aureooms-js-array/src/sort.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/sorted.js~sorted",
    "function/index.html#static-function-sorted",
    "<span>sorted</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/sorted.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/splice.js~splice",
    "function/index.html#static-function-splice",
    "<span>splice</span> <span class=\"search-result-import-path\">aureooms-js-array/src/splice.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/starmap.js~starmap",
    "function/index.html#static-function-starmap",
    "<span>starmap</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/starmap.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/reduce/sum.js~sum",
    "function/index.html#static-function-sum",
    "<span>sum</span> <span class=\"search-result-import-path\">aureooms-js-array/src/reduce/sum.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/swap.js~swap",
    "function/index.html#static-function-swap",
    "<span>swap</span> <span class=\"search-result-import-path\">aureooms-js-array/src/swap.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/swapranges.js~swapranges",
    "function/index.html#static-function-swapranges",
    "<span>swapranges</span> <span class=\"search-result-import-path\">aureooms-js-array/src/swapranges.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/takewhile.js~takewhile",
    "function/index.html#static-function-takewhile",
    "<span>takewhile</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/takewhile.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/utils/tee.js~tee",
    "function/index.html#static-function-tee",
    "<span>tee</span> <span class=\"search-result-import-path\">aureooms-js-array/src/utils/tee.js</span>",
    "function"
  ],
  [
    "aureooms-js-array/src/map/zip.js~zip",
    "function/index.html#static-function-zip",
    "<span>zip</span> <span class=\"search-result-import-path\">aureooms-js-array/src/map/zip.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/alloc.js",
    "file/src/alloc.js.html",
    "src/alloc.js",
    "file"
  ],
  [
    "src/argmax.js",
    "file/src/argmax.js.html",
    "src/argmax.js",
    "file"
  ],
  [
    "src/argmin.js",
    "file/src/argmin.js.html",
    "src/argmin.js",
    "file"
  ],
  [
    "src/copy.js",
    "file/src/copy.js.html",
    "src/copy.js",
    "file"
  ],
  [
    "src/each.js",
    "file/src/each.js.html",
    "src/each.js",
    "file"
  ],
  [
    "src/fill.js",
    "file/src/fill.js.html",
    "src/fill.js",
    "file"
  ],
  [
    "src/fillfn.js",
    "file/src/fillfn.js.html",
    "src/fillfn.js",
    "file"
  ],
  [
    "src/get.js",
    "file/src/get.js.html",
    "src/get.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/iota.js",
    "file/src/iota.js.html",
    "src/iota.js",
    "file"
  ],
  [
    "src/map/chain.js",
    "file/src/map/chain.js.html",
    "src/map/chain.js",
    "file"
  ],
  [
    "src/map/combinations.js",
    "file/src/map/combinations.js.html",
    "src/map/combinations.js",
    "file"
  ],
  [
    "src/map/combinationswithrepetition.js",
    "file/src/map/combinationswithrepetition.js.html",
    "src/map/combinationswithrepetition.js",
    "file"
  ],
  [
    "src/map/compress.js",
    "file/src/map/compress.js.html",
    "src/map/compress.js",
    "file"
  ],
  [
    "src/map/dropwhile.js",
    "file/src/map/dropwhile.js.html",
    "src/map/dropwhile.js",
    "file"
  ],
  [
    "src/map/enumerate.js",
    "file/src/map/enumerate.js.html",
    "src/map/enumerate.js",
    "file"
  ],
  [
    "src/map/filter.js",
    "file/src/map/filter.js.html",
    "src/map/filter.js",
    "file"
  ],
  [
    "src/map/filterfalse.js",
    "file/src/map/filterfalse.js.html",
    "src/map/filterfalse.js",
    "file"
  ],
  [
    "src/map/group.js",
    "file/src/map/group.js.html",
    "src/map/group.js",
    "file"
  ],
  [
    "src/map/index.js",
    "file/src/map/index.js.html",
    "src/map/index.js",
    "file"
  ],
  [
    "src/map/islice.js",
    "file/src/map/islice.js.html",
    "src/map/islice.js",
    "file"
  ],
  [
    "src/map/map.js",
    "file/src/map/map.js.html",
    "src/map/map.js",
    "file"
  ],
  [
    "src/map/permutations.js",
    "file/src/map/permutations.js.html",
    "src/map/permutations.js",
    "file"
  ],
  [
    "src/map/product.js",
    "file/src/map/product.js.html",
    "src/map/product.js",
    "file"
  ],
  [
    "src/map/repeat.js",
    "file/src/map/repeat.js.html",
    "src/map/repeat.js",
    "file"
  ],
  [
    "src/map/reversed.js",
    "file/src/map/reversed.js.html",
    "src/map/reversed.js",
    "file"
  ],
  [
    "src/map/sorted.js",
    "file/src/map/sorted.js.html",
    "src/map/sorted.js",
    "file"
  ],
  [
    "src/map/starmap.js",
    "file/src/map/starmap.js.html",
    "src/map/starmap.js",
    "file"
  ],
  [
    "src/map/takewhile.js",
    "file/src/map/takewhile.js.html",
    "src/map/takewhile.js",
    "file"
  ],
  [
    "src/map/zip.js",
    "file/src/map/zip.js.html",
    "src/map/zip.js",
    "file"
  ],
  [
    "src/max.js",
    "file/src/max.js.html",
    "src/max.js",
    "file"
  ],
  [
    "src/min.js",
    "file/src/min.js.html",
    "src/min.js",
    "file"
  ],
  [
    "src/realloc.js",
    "file/src/realloc.js.html",
    "src/realloc.js",
    "file"
  ],
  [
    "src/reduce/all.js",
    "file/src/reduce/all.js.html",
    "src/reduce/all.js",
    "file"
  ],
  [
    "src/reduce/any.js",
    "file/src/reduce/any.js.html",
    "src/reduce/any.js",
    "file"
  ],
  [
    "src/reduce/index.js",
    "file/src/reduce/index.js.html",
    "src/reduce/index.js",
    "file"
  ],
  [
    "src/reduce/reduce.js",
    "file/src/reduce/reduce.js.html",
    "src/reduce/reduce.js",
    "file"
  ],
  [
    "src/reduce/sum.js",
    "file/src/reduce/sum.js.html",
    "src/reduce/sum.js",
    "file"
  ],
  [
    "src/repr.js",
    "file/src/repr.js.html",
    "src/repr.js",
    "file"
  ],
  [
    "src/reverse.js",
    "file/src/reverse.js.html",
    "src/reverse.js",
    "file"
  ],
  [
    "src/rotate.js",
    "file/src/rotate.js.html",
    "src/rotate.js",
    "file"
  ],
  [
    "src/set.js",
    "file/src/set.js.html",
    "src/set.js",
    "file"
  ],
  [
    "src/slice.js",
    "file/src/slice.js.html",
    "src/slice.js",
    "file"
  ],
  [
    "src/sort.js",
    "file/src/sort.js.html",
    "src/sort.js",
    "file"
  ],
  [
    "src/splice.js",
    "file/src/splice.js.html",
    "src/splice.js",
    "file"
  ],
  [
    "src/swap.js",
    "file/src/swap.js.html",
    "src/swap.js",
    "file"
  ],
  [
    "src/swapranges.js",
    "file/src/swapranges.js.html",
    "src/swapranges.js",
    "file"
  ],
  [
    "src/utils/index.js",
    "file/src/utils/index.js.html",
    "src/utils/index.js",
    "file"
  ],
  [
    "src/utils/pick.js",
    "file/src/utils/pick.js.html",
    "src/utils/pick.js",
    "file"
  ],
  [
    "src/utils/range.js",
    "file/src/utils/range.js.html",
    "src/utils/range.js",
    "file"
  ],
  [
    "src/utils/tee.js",
    "file/src/utils/tee.js.html",
    "src/utils/tee.js",
    "file"
  ]
]